version: '2'
services:
  db:
    ports:
      - '5432:5432'
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'password'
  web-dtse:
    mem_limit: '1012m'
    mem_reservation: '512M'
    container_name: "backend_dtse"
    build: .
    command: python manage.py runserver 0.0.0.0:8100
    volumes:
      - .:/code
    ports:
      - "8100:8100"
    depends_on:
      - db

volumes:
  postgres_data: